title: Project Proper
description: Finding the most private and secure way to use technology.
url: https://proper.enriquerdl.com # https://proper.enriquerdl.com  # http://localhost:4000
permalink: /:categories/:title
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Enrique"
