title: Project Proper
description: Finding the most private and secure way to use technology.
url: 127.0.0.1:4000
permalink: /:categories/:title
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Enrique"
